
IF "%CONTAINER_GROUP%"=="" SET CONTAINER_GROUP=openwebui
IF "%CONTAINER_OLLAMA_NAME%"=="" SET CONTAINER_OLLAMA_NAME=ollama
IF "%CONTAINER_OLLAMA_MODELS%"=="" SET CONTAINER_OLLAMA_MODELS=phi3 llama3.2 llava-phi3
