services:

  tika:
    extends:
      file: docker-compose.apache-tika.yaml
      service: tika
    networks:
      - backend

  ollama:
    extends:
      file: docker-compose.ollama.yaml
      service: ollama
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    extends:
      file: docker-compose.open-webui.yaml
      service: open-webui
    depends_on:
      - ollama
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
