services:
  open-webui:
    container_name: 'open-webui'
    image: 'ghcr.io/open-webui/open-webui:main'
    volumes:
      - './open-webui:/app/backend/data:rw'
      - './config.yaml:/app/backend/data/litellm/config.yaml:ro'
      - './docs:/app/backend/data/docs:rw'
    ports:
      - '3003:8080'
    environment:
      DEFAULT_MODELS: 'llama3-70b-8192'
      OPENAI_API_BASE_URLS: 'https://api.groq.com/openai/v1'
      OPENAI_API_KEYS: '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'
      PDF_EXTRACT_IMAGES: True
      # WEBUI_AUTH: false
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    restart: 'unless-stopped'

  